/**
  * @file bq28z.c
  * @author generated by mrt-device utility 
  * @link [https://github.com/uprev-mrt/mrtutils/wiki/mrt-device]
  * @brief Device driver for BQ28Z device
  *
  */

#include "bq28z.h"



/**
 * @brief initializes device
 * @param dev ptr to BQ28Z device
 * @return status 
 */
static mrt_status_t bq28z_init(bq28z_t* dev)
{   
    /* Initialize Register Descriptors */
    REG_INIT( dev->mDummy , BQ28Z_REG_DUMMY_ADDR , uint16_t, REG_PERM_R , 0xDEAD  );
    REG_INIT( dev->mManufactureraccessControlstatus , BQ28Z_REG_MANUFACTURERACCESS_CONTROLSTATUS_ADDR , uint16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mAtrate , BQ28Z_REG_ATRATE_ADDR , int16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mAtratetimetoempty , BQ28Z_REG_ATRATETIMETOEMPTY_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mTemperature , BQ28Z_REG_TEMPERATURE_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mVoltage , BQ28Z_REG_VOLTAGE_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mBatterystatus , BQ28Z_REG_BATTERYSTATUS_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mCurrent , BQ28Z_REG_CURRENT_ADDR , int16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mMaxerror , BQ28Z_REG_MAXERROR_ADDR , uint8_t, REG_PERM_R , 0x00  );
    REG_INIT( dev->mRemainingcapacity , BQ28Z_REG_REMAININGCAPACITY_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mFullchargecapacity , BQ28Z_REG_FULLCHARGECAPACITY_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mAveragecurrent , BQ28Z_REG_AVERAGECURRENT_ADDR , int16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mAveragetimetoempty , BQ28Z_REG_AVERAGETIMETOEMPTY_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mAveragetimetofull , BQ28Z_REG_AVERAGETIMETOFULL_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mStandbycurrent , BQ28Z_REG_STANDBYCURRENT_ADDR , int16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mStandbytimetoempty , BQ28Z_REG_STANDBYTIMETOEMPTY_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mMaxloadcurrent , BQ28Z_REG_MAXLOADCURRENT_ADDR , int16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mMaxloadtimetoempty , BQ28Z_REG_MAXLOADTIMETOEMPTY_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mAveragepower , BQ28Z_REG_AVERAGEPOWER_ADDR , int16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mBtpdischargeset , BQ28Z_REG_BTPDISCHARGESET_ADDR , int16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mBtpchargeset , BQ28Z_REG_BTPCHARGESET_ADDR , int16_t, REG_PERM_RW , 0x0000  );
    REG_INIT( dev->mInternaltemperature , BQ28Z_REG_INTERNALTEMPERATURE_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mCyclecount , BQ28Z_REG_CYCLECOUNT_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mRelativestateofcharge , BQ28Z_REG_RELATIVESTATEOFCHARGE_ADDR , uint8_t, REG_PERM_R , 0x00  );
    REG_INIT( dev->mStateofhealth , BQ28Z_REG_STATEOFHEALTH_ADDR , uint8_t, REG_PERM_R , 0x00  );
    REG_INIT( dev->mChargevoltage , BQ28Z_REG_CHARGEVOLTAGE_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mChargecurrent , BQ28Z_REG_CHARGECURRENT_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mDesigncapacity , BQ28Z_REG_DESIGNCAPACITY_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mAltmanufactureraccess , BQ28Z_REG_ALTMANUFACTURERACCESS_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mMacdata , BQ28Z_REG_MACDATA_ADDR , uint16_t, REG_PERM_R , 0x0000  );
    REG_INIT( dev->mSafetyalert , BQ28Z_REG_SAFETYALERT_ADDR , uint32_t, REG_PERM_R , 0x00000000  );
    REG_INIT( dev->mMacdatasum , BQ28Z_REG_MACDATASUM_ADDR , uint8_t, REG_PERM_R , 0x00  );
    REG_INIT( dev->mMacdatalen , BQ28Z_REG_MACDATALEN_ADDR , uint8_t, REG_PERM_R , 0x00  );


    /*user-block-init-start*/
    // this is the stuff that I added

    //bq28z_set_btpchargeset(dev, 1000);
    //bq28z_set_btpdischargeset(dev,1000);
    /*user-block-init-end*/

    return MRT_STATUS_OK;
}


mrt_status_t bq28z_init_i2c(bq28z_t* dev, mrt_i2c_handle_t i2c)
{
    mrt_status_t status;

    status = init_i2c_register_device(&dev->mRegDev, i2c, BQ28Z_I2C_ADDRESS, BQ28Z_REG_ADDR_SIZE );

    bq28z_init(dev);


    /*user-block-init-i2c-start*/
    /*user-block-init-i2c-end*/
    
    return status;
}

mrt_status_t bq28z_test(bq28z_t* dev)
{
    mrt_status_t status = MRT_STATUS_ERROR;

    /*user-block-test-start*/
    uint16_t voltage = bq28z_get_voltage(dev);

    if(voltage > 0)
    {
        status = MRT_STATUS_OK;
    }
    /*user-block-test-end*/
    return status;
}


/*user-block-bottom-start*/

/**
  *@brief unseal memory
  *@param dev ptr to BQ28Z device
  */
mrt_status_t bq28z_unseal(bq28z_t* dev);

/**
  *@brief seal memory
  *@param dev ptr to BQ28Z device
  */
mrt_status_t bq28z_seal(bq28z_t* dev);

/*user-block-bottom-end*/
